"""empty message

Revision ID: 2ae1068ac2b9
Revises: c8970c5db626
Create Date: 2018-08-22 00:16:09.659214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ae1068ac2b9'
down_revision = 'c8970c5db626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('base_url', sa.String(length=2048), nullable=False),
    sa.Column('stub_url', sa.String(length=2048), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_base_url'), 'comments', ['base_url'], unique=False)
    op.create_index(op.f('ix_comments_email'), 'comments', ['email'], unique=False)
    op.create_index(op.f('ix_comments_name'), 'comments', ['name'], unique=False)
    op.create_index(op.f('ix_comments_stub_url'), 'comments', ['stub_url'], unique=False)
    op.create_index(op.f('ix_comments_time_created'), 'comments', ['time_created'], unique=False)
    op.drop_index('ix_comment_base_url', table_name='comment')
    op.drop_index('ix_comment_email', table_name='comment')
    op.drop_index('ix_comment_stub_url', table_name='comment')
    op.drop_index('ix_comment_time_created', table_name='comment')
    op.drop_table('comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('comment', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('time_created', sa.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('time_updated', sa.DATETIME(), nullable=True),
    sa.Column('approved', sa.BOOLEAN(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('base_url', sa.VARCHAR(length=2048), nullable=True),
    sa.Column('stub_url', sa.VARCHAR(length=2048), nullable=True),
    sa.CheckConstraint('active IN (0, 1)'),
    sa.CheckConstraint('approved IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comment_time_created', 'comment', ['time_created'], unique=False)
    op.create_index('ix_comment_stub_url', 'comment', ['stub_url'], unique=False)
    op.create_index('ix_comment_email', 'comment', ['email'], unique=False)
    op.create_index('ix_comment_base_url', 'comment', ['base_url'], unique=False)
    op.drop_index(op.f('ix_comments_time_created'), table_name='comments')
    op.drop_index(op.f('ix_comments_stub_url'), table_name='comments')
    op.drop_index(op.f('ix_comments_name'), table_name='comments')
    op.drop_index(op.f('ix_comments_email'), table_name='comments')
    op.drop_index(op.f('ix_comments_base_url'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
