"""comment table

Revision ID: c8970c5db626
Revises: 
Create Date: 2018-08-19 08:52:07.958200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8970c5db626'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('base_url', sa.String(length=2048), nullable=True),
    sa.Column('stub_url', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_base_url'), 'comment', ['base_url'], unique=False)
    op.create_index(op.f('ix_comment_email'), 'comment', ['email'], unique=False)
    op.create_index(op.f('ix_comment_stub_url'), 'comment', ['stub_url'], unique=False)
    op.create_index(op.f('ix_comment_time_created'), 'comment', ['time_created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_time_created'), table_name='comment')
    op.drop_index(op.f('ix_comment_stub_url'), table_name='comment')
    op.drop_index(op.f('ix_comment_email'), table_name='comment')
    op.drop_index(op.f('ix_comment_base_url'), table_name='comment')
    op.drop_table('comment')
    # ### end Alembic commands ###
